service: mysteam-server

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  memorySize: 1024

package:
  exclude:
  - node_modules/**/*.ts
  - node_modules/aws-sdk/.changes/**
  - node_modules/aws-sdk/dist/**
  - node_modules/typescript/**

functions:
  service:
    handler: service.handle
    events:
    - http:
        path: api/{method}
        method: get
        cors: true
    - http:
        path: api/{method}
        method: post
        cors: true

plugins:
  - serverless-offline
