name: My Steam Games server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.18.1
      - run: envsubst < config.ts > .config.ts
        env:
          STEAM_KEY: ${{ secrets.STEAM_KEY }}
          TWITCH_EXTENSION_SECRET: ${{ secrets.TWITCH_EXTENSION_SECRET }}
      - run: mv .config.ts config.ts
      - run: npm install --save-dev
      - run: $(npm bin)/tslint --project tsconfig.json --config tslint.yaml
      - run: $(npm bin)/tsc
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: $(npm bin)/serverless deploy --stage production

