name: My Steam Games server

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: envsubst < config.ts > .config.ts
      - run: mv .config.ts config.ts
      - run: npm install --save-dev
      - run: ./node_modules/.bin/tslint --project tsconfig.json --config tslint.yaml
      - run: tsc
